-- AI Trading Assistant Platform — PostgreSQL schema

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Accounts
CREATE TABLE IF NOT EXISTS accounts (
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    capital DECIMAL(18, 2) NOT NULL DEFAULT 100000,
    broker VARCHAR(32) NOT NULL DEFAULT 'paper',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Risk state per account (daily limits, kill switch)
CREATE TABLE IF NOT EXISTS risk_state (
    id SERIAL PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    trade_date DATE NOT NULL,
    daily_pnl DECIMAL(18, 2) NOT NULL DEFAULT 0,
    trades_today INTEGER NOT NULL DEFAULT 0,
    peak_equity DECIMAL(18, 2) NOT NULL,
    current_drawdown_pct DECIMAL(8, 4) NOT NULL DEFAULT 0,
    kill_switch_active BOOLEAN NOT NULL DEFAULT FALSE,
    kill_switch_reason TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (account_id, trade_date)
);

-- Signals generated by strategy engine
CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    account_id INTEGER REFERENCES accounts(id),
    symbol VARCHAR(32) NOT NULL,
    exchange VARCHAR(8) NOT NULL DEFAULT 'NSE',
    direction VARCHAR(8) NOT NULL,
    setup_type VARCHAR(64) NOT NULL,
    entry_price DECIMAL(18, 4) NOT NULL,
    stop_loss DECIMAL(18, 4) NOT NULL,
    target_price DECIMAL(18, 4) NOT NULL,
    risk_reward DECIMAL(8, 4) NOT NULL,
    confidence DECIMAL(5, 2) NOT NULL,
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    rejection_reasons JSONB DEFAULT '[]',
    technical_snapshot JSONB,
    ai_reasoning JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_signals_symbol_created ON signals(symbol, created_at DESC);
CREATE INDEX idx_signals_account ON signals(account_id);

-- Trades (paper or live)
CREATE TABLE IF NOT EXISTS trades (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    signal_id UUID REFERENCES signals(id),
    account_id INTEGER NOT NULL REFERENCES accounts(id),
    symbol VARCHAR(32) NOT NULL,
    exchange VARCHAR(8) NOT NULL DEFAULT 'NSE',
    direction VARCHAR(8) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'open',
    entry_price DECIMAL(18, 4),
    exit_price DECIMAL(18, 4),
    stop_loss DECIMAL(18, 4) NOT NULL,
    target_price DECIMAL(18, 4) NOT NULL,
    quantity INTEGER NOT NULL,
    pnl DECIMAL(18, 2),
    pnl_pct DECIMAL(8, 4),
    is_paper BOOLEAN NOT NULL DEFAULT TRUE,
    opened_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trades_account_status ON trades(account_id, status);
CREATE INDEX idx_trades_symbol ON trades(symbol);

-- Execution logs
CREATE TABLE IF NOT EXISTS execution_logs (
    id SERIAL PRIMARY KEY,
    trade_id UUID REFERENCES trades(id),
    broker VARCHAR(32) NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    request_payload JSONB,
    response_payload JSONB,
    status VARCHAR(32) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Backtest runs
CREATE TABLE IF NOT EXISTS backtest_runs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    strategy_name VARCHAR(128) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    parameters JSONB,
    metrics JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Alert history
CREATE TABLE IF NOT EXISTS alert_logs (
    id SERIAL PRIMARY KEY,
    channel VARCHAR(32) NOT NULL DEFAULT 'telegram',
    payload TEXT NOT NULL,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Broker access tokens
CREATE TABLE IF NOT EXISTS broker_tokens (
    id SERIAL PRIMARY KEY,
    broker VARCHAR(32) NOT NULL,
    account_id INTEGER REFERENCES accounts(id),
    access_token TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Default paper account
INSERT INTO accounts (name, capital, broker)
SELECT 'Paper Trading', 100000, 'paper'
WHERE NOT EXISTS (SELECT 1 FROM accounts WHERE name = 'Paper Trading');
